Opanas
toleksyn/taqc-542 pull request #12
Opened 2020-11-23 18:37 UTC by panas224

Fixed

2020-11-24 09:47 UTC, toleksyn requested changes

2020-11-24 09:47 UTC, toleksyn commented on src/test/java/panas224/Calculation.java
> +package panas224;
rename

2020-11-24 09:47 UTC, toleksyn commented on src/test/java/panas224/Calculation.java
> +    public int calculate(int n)
rename

2020-11-24 10:01 UTC, panas224 commented on src/test/java/panas224/Calculation.java
> +package panas224;
already renamed

2020-11-25 07:24 UTC, toleksyn requested changes

2020-11-25 07:24 UTC, toleksyn commented on src/test/java/opanas/task_01/Calculation.java
> +        return x0;
rename method names and variables

2020-11-25 07:37 UTC, toleksyn requested changes

2020-11-25 07:37 UTC, toleksyn commented on src/test/java/opanas/task_01/CalculationTest.java
> +    public void CalculatingTest(int expected,int origin) {
test method start with verify()

2020-11-25 09:05 UTC, panas224 commented on src/test/java/opanas/task_01/Calculation.java
> +        return x0;
done

2020-11-26 09:08 UTC, toleksyn requested changes

2020-11-26 09:08 UTC, toleksyn commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
remove

2020-11-26 09:08 UTC, toleksyn commented on src/test/java/opanas/task_02/SignInTest.java
> +        WebElement LogInEmail=driver.findElement(By.id("email"));
code convention

2020-11-26 09:20 UTC, panas224 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done

2020-11-26 09:21 UTC, panas224 commented on src/test/java/opanas/task_02/SignInTest.java
> +        WebElement LogInEmail=driver.findElement(By.id("email"));
done

2020-11-26 13:24 UTC, toleksyn requested changes

2020-11-26 13:24 UTC, toleksyn commented on src/test/java/opanas/task_02/SignInTest.java
> +    private void verifyForgotPassword()  {
always public

2020-11-27 10:00 UTC, toleksyn requested changes

2020-11-27 10:00 UTC, toleksyn commented on src/test/java/opanas/task_02/SignInTest.java
> +        System.out.println(handles);
no sys out prints

2020-11-30 07:33 UTC, toleksyn requested changes

2020-11-30 07:33 UTC, toleksyn commented on build.gradle
>  }
no need to add custom labels

2020-11-30 07:33 UTC, toleksyn commented on src/test/java/opanas/task_01/CalculationTest.java
> +    public Object[][] GetData(){
java code convention

2020-12-10 07:49 UTC, merged